/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Ui5Component {
        "componentName": string;
        "componentUrl": string;
    }
}
declare global {
    interface HTMLUi5ComponentElement extends Components.Ui5Component, HTMLStencilElement {
    }
    var HTMLUi5ComponentElement: {
        prototype: HTMLUi5ComponentElement;
        new (): HTMLUi5ComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ui5-component": HTMLUi5ComponentElement;
    }
}
declare namespace LocalJSX {
    interface Ui5Component {
        "componentName"?: string;
        "componentUrl"?: string;
        "onLoadingError"?: (event: CustomEvent<any>) => void;
        "onUi5Message"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "ui5-component": Ui5Component;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui5-component": LocalJSX.Ui5Component & JSXBase.HTMLAttributes<HTMLUi5ComponentElement>;
        }
    }
}
